spring:
  application:
    name: maas-bpm
  # data source config
  datasource:
    #    url: jdbc:h2:file:./camunda;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:mem:camunda
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

#Camunda config
camunda.bpm:
  history-level: full
  filter:
    create: All tasks
  admin-user:
    id: admin
    password: admin
    email: admin@camunda.com
    first-name: Camunda
    last-name: Admin