server:
  port: 8761

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  enabled: true
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    healthcheck:
      enabled: true