server:
  port: 8080

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  enabled: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: false

maas:
  api:
    server: http://localhost:8081

info:
  rednavis:
    email: info@rednavis.com