server:
  port: 0

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  data:
    mongodb:
      database: maas
      host: localhost
      port: 27017
      auto-index-creation: true

eureka:
  enabled: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: false